export default catchError = (req, res, next) => {
  try {
  } catch (error) {}
};
